// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-_67QlFtN59ZFN6ay1UFym-l2mPXtI0Y',
    appId: '1:80479463864:web:aba13ddcc90fca7f1fc74d',
    messagingSenderId: '80479463864',
    projectId: 'soutenance-6fd64',
    authDomain: 'soutenance-6fd64.firebaseapp.com',
    storageBucket: 'soutenance-6fd64.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQUU4HnYXXpPW8sDMFffd5gOkcUaQejH8',
    appId: '1:80479463864:android:00e374172cd080031fc74d',
    messagingSenderId: '80479463864',
    projectId: 'soutenance-6fd64',
    storageBucket: 'soutenance-6fd64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1cwPNX52FtZbpB-tdfNgAbGtMjc5tsEs',
    appId: '1:80479463864:ios:7c26a22b39272c4a1fc74d',
    messagingSenderId: '80479463864',
    projectId: 'soutenance-6fd64',
    storageBucket: 'soutenance-6fd64.firebasestorage.app',
    iosBundleId: 'com.sante.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1cwPNX52FtZbpB-tdfNgAbGtMjc5tsEs',
    appId: '1:80479463864:ios:7c26a22b39272c4a1fc74d',
    messagingSenderId: '80479463864',
    projectId: 'soutenance-6fd64',
    storageBucket: 'soutenance-6fd64.firebasestorage.app',
    iosBundleId: 'com.sante.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-_67QlFtN59ZFN6ay1UFym-l2mPXtI0Y',
    appId: '1:80479463864:web:b96985c72dacff151fc74d',
    messagingSenderId: '80479463864',
    projectId: 'soutenance-6fd64',
    authDomain: 'soutenance-6fd64.firebaseapp.com',
    storageBucket: 'soutenance-6fd64.firebasestorage.app',
  );
}
